<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HollowRun</AssemblyName>
    <RootNamespace>HollowRun.Launcher</RootNamespace>
  </PropertyGroup>

</Project>
